baseURL = "https://25349023.github.io/ADUDA/"
languageCode = "en-us"
title = "ADUDA"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Detail"
  url = "/detail/"
  weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/ADUDA/detail'
  homepage_button_text = 'Read More'
  homepage_intro = 'ADUDA: Autonomous Driving with Unsupervised Domain Adaptation for Semantic Segmentation'
  homepage_image = ''

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "ADUDA: Autonomous Driving with Unsupervised Domain Adaptation for Semantic Segmentation"
    meta_og_title = "ADUDA"
    meta_og_type = "website"
    meta_og_url = "https://25349023.github.io/ADUDA"
    meta_og_image = ""
    meta_og_description = "ADUDA: Autonomous Driving with Unsupervised Domain Adaptation for Semantic Segmentation"

  [params.logo]
    mobile = "husky_logo.png"
    standard  = "husky_logo.png"
